services:
  app:
    image: vlmontegrande/health-endpoint:latest
    restart: unless-stopped
    ports:
      - "8084:8080"
    environment:
      NODE_ENV: production
      PORT: 8080
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
    volumes:
      - /:/rootfs:ro
      - /run/utmp:/run/utmp:ro
